---
- name: Converge
  hosts: all
  vars:
    # svc compose volumes dir to create
    compose_deploy_volumes_dir:
      - path: /app/nginx
        mode: "0755"


    # files to use as configuration
    compose_deploy_config_files:
      - src: files/nginx/nginx.conf
        dest: /app/nginx

    # use ssl self-signed
    compose_deploy_use_selfsigned_ssl: true
    compose_deploy_domain_names:
      - name: "localhost"

    # compose files
    compose_deploy_manifests:
      - src: files/compose/docker-compose.yml
        dest: /app/

  pre_tasks:
    - name: "Install iproute2 packages"
      ansible.builtin.package:
        name: "iproute2"
        state: present

  roles:
    - role: bngameni.compose_deploy
