---
dependency:
  name: shell
  command: pip install requests

driver:
  name: docker

platforms:
  # On "${name:-${image:-debian}", the last brace does not miss, it works like that...
  # The env var should be used when the image variable refers to a full registry path like registry.access.redhat.com/ubi8/ubi
  - name: bngameni_compose_deploy_${name:-${image:-debian}-${tag:-latest}-${scenario:-default}
    image: ${image:-debian}:${tag:-latest}
    privileged: true
    pre_build_image: true
    tty: true

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true

verifier:
  name: testinfra
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
