---
name: Ansible Molecule

on:  # yamllint disable-line rule:truthy
  push:
    tags_ignore:
      - '*'
  pull_request:

env:
  PYTHON_VERSION: "3.13"

jobs:
  setup:
    name: Setup scenarios matrix
    runs-on: ubuntu-22.04
    outputs:
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          JSON="["

          for s in $(find molecule -mindepth 1 -maxdepth 1 -type d -exec basename "{}" \;); do
            if [ -e "molecule/${s}/molecule.yml" ]; then
            # if [ ${s} = "default" ]; then # for local test with act
              JSON="${JSON}\"${s}\","
            fi
          done

          JSON="${JSON%?}"
          JSON="$JSON]"

          echo "::set-output name=scenarios::$(echo $JSON)"

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: "${{ github.repository }}"
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: "${{ github.repository }}/requirements.txt"
      - name: install lint dependencies
        working-directory: "${{ github.repository }}"
        run: |
          python -V
          python -m pip install --root-user-action ignore --upgrade pip
          python -m pip install --root-user-action ignore -r requirements.txt
      - name: yamllint
        working-directory: "${{ github.repository }}"
        run: yamllint .
      - name: ansible-lint
        working-directory: "${{ github.repository }}"
        run: ansible-lint

  test:
    name: Scenario "${{ matrix.scenario }}" on ${{ matrix.config.image }}:${{ matrix.config.tag }}
    needs:
      - lint
      - setup
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.setup.outputs.scenarios) }}
        config:
          - image: "dcagatay/ubuntu-dind"
            tag: "22.04"

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: "${{ github.repository }}"
      - name: Set correct right to docker.
        run: sudo chmod 666 /var/run/docker.sock
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          scenario: ${{ matrix.scenario }}
        env:
          name: ${{ matrix.config.name }}
